/**
 * Fuwari 主题配置
 */
const CONFIG = {
  FUWARI_MENU_INDEX: true,
  FUWARI_MENU_CATEGORY: true,
  FUWARI_MENU_TAG: true,
  FUWARI_MENU_ARCHIVE: true,
  FUWARI_MENU_SEARCH: true,

  FUWARI_POST_LIST_COVER: true,
  FUWARI_POST_LIST_COVER_DEFAULT: true,
  FUWARI_POST_LIST_COVER_HOVER_ENLARGE: true,
  FUWARI_POST_LIST_SUMMARY: true,
  FUWARI_POST_LIST_TAG: true,

  FUWARI_MOBILE_MENU: true,
  FUWARI_HOME_INTRO_TITLE: 'Latest Articles',
  FUWARI_HOME_INTRO_SUBTITLE: 'Journal',
  FUWARI_HERO_ENABLE: true,
  FUWARI_HERO_BADGE: 'From Notion Database',
  FUWARI_HERO_BG_IMAGE: '',
  FUWARI_HERO_CREDIT_TEXT: '',
  FUWARI_HERO_CREDIT_LINK: '',

  FUWARI_WIDGET_NOTICE: true,
  FUWARI_WIDGET_LATEST_POSTS: true,
  FUWARI_WIDGET_CATEGORY_LIST: true,
  FUWARI_WIDGET_TAG_LIST: true,
  FUWARI_PROFILE_PATH: '/about',
  FUWARI_WIDGET_CONTACT: true,
  FUWARI_CONTACT_TITLE: 'Contact',
  FUWARI_CONTACT_DESCRIPTION: 'Join the community and discuss ideas.',
  FUWARI_CONTACT_URL: 'https://docs.tangly1024.com/article/how-to-question',
  FUWARI_CONTACT_TEXT: 'Get in touch',
  FUWARI_CONTACT_FLIP_CARD: true,
  FUWARI_CONTACT_BACK_TITLE: 'Keep in touch',
  FUWARI_CONTACT_BACK_DESCRIPTION: 'Share your ideas, collaboration, and feedback anytime.',
  FUWARI_CONTACT_BACK_TEXT: 'Open Contact',
  FUWARI_WIDGET_AD: false,
  FUWARI_WIDGET_WWADS: true,
  FUWARI_WIDGET_ADSENSE: false,
  FUWARI_WIDGET_PLUGIN_AREA: true,
  FUWARI_WIDGET_ANALYTICS: true,
  FUWARI_WIDGET_THEME_COLOR_SWITCHER: true,
  FUWARI_THEME_COLOR_HUE: 52, // 0~360, default brand hue
  FUWARI_THEME_COLOR_FIXED: false, // true = hide palette picker for visitors
  FUWARI_WIDGET_TO_COMMENT: true,
  FUWARI_WIDGET_DARK_MODE: true,
  FUWARI_ARTICLE_TOC: true,
  FUWARI_EFFECT_LENIS: false,
  FUWARI_EFFECT_CURSOR_DOT: false,

  FUWARI_ARTICLE_META: true,
  FUWARI_ARTICLE_SHARE: true,
  FUWARI_ARTICLE_COPYRIGHT: true,
  FUWARI_ARTICLE_COMMENT: true,
  FUWARI_ARTICLE_ADJACENT: true
}

export default CONFIG

