#!/bin/bash
pIDa=`/usr/sbin/lsof -i :9000|grep -v "PID" | awk '{print $2}'`
if [ "$pIDa" != "" ];
then
   echo "1"
else
  cp -r . /tmp
  cd /tmp
  export PORT=9000
  /var/lang/node16/bin/node start.js
  #node ./start.js
fi
