#!/var/lang/node16/bin/node
// const { nextStart } = require('next/dist/cli/next-start')
// nextStart(['-p', '9000', '--hostname', '0.0.0.0'])
// 需要设置环境变量 PORT 9000
require('next/dist/cli/next-start')
