const CONFIG = {

  SIMPLE_LOGO_IMG: '/Logo.webp',
  SIMPLE_TOP_BAR: true, // 显示顶栏
  SIMPLE_TOP_BAR_CONTENT: process.env.NEXT_PUBLIC_THEME_SIMPLE_TOP_TIPS || '',
  SIMPLE_LOGO_DESCRIPTION: process.env.NEXT_PUBLIC_THEME_SIMPLE_LOGO_DESCRIPTION || '<div>泛设计学科学生<br/>用户研究员<br/>关心服务的一切</div>',

  SIMPLE_AUTHOR_LINK: process.env.NEXT_PUBLIC_AUTHOR_LINK || '#',

  SIMPLE_HOME_INTERDISCIPLINARY_CENTER:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_CENTER || '我的交叉学习图谱',
  SIMPLE_HOME_TITLE_TEXT:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_TITLE_TEXT || 'Chengliang',
  SIMPLE_HOME_INTRO_HTML:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_INTRO || '',
  SIMPLE_HOME_SIGNATURE_TEXT:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_SIGNATURE_TEXT || 'pcl2design',
  SIMPLE_HOME_FRAME_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_FRAME_IMAGE || '',
  SIMPLE_HOME_LAYER_MAIN_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_MAIN_IMAGE || '',
  SIMPLE_HOME_LAYER_GROUND_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_GROUND_IMAGE || '',
  SIMPLE_HOME_LAYER_ARCHITECTURE_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_ARCHITECTURE_IMAGE || '/api/pcl-asset?key=architecture',
  SIMPLE_HOME_LAYER_VISUAL_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_VISUAL_IMAGE || '/api/pcl-asset?key=visual',
  SIMPLE_HOME_LAYER_HCI_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_HCI_IMAGE || '/api/pcl-asset?key=hci',
  SIMPLE_HOME_LAYER_SERVICE_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_SERVICE_IMAGE || '/api/pcl-asset?key=service',
  SIMPLE_HOME_LAYER_UX_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_UX_IMAGE || '/api/pcl-asset?key=ux',
  SIMPLE_HOME_LAYER_IXD_IMAGE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LAYER_IXD_IMAGE || '/api/pcl-asset?key=ixd',
  SIMPLE_HOME_HOTSPOTS:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_HOTSPOTS || '',
  SIMPLE_HOME_SUBMENU_PARENT:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_SUBMENU_PARENT || '',
  SIMPLE_HOME_NODE_ALIASES:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_NODE_ALIASES || '',
  SIMPLE_HOME_LEFT_PNG:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_LEFT_PNG || '',
  SIMPLE_HOME_BOTTOM_PNG:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_BOTTOM_PNG || '',
  SIMPLE_HOME_MAP_FONT_SIZE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_MAP_FONT_SIZE || 16,
  SIMPLE_HOME_TITLE_FONT_SIZE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_TITLE_FONT_SIZE || 16,
  SIMPLE_HOME_BODY_FONT_SIZE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_BODY_FONT_SIZE || 16,
  SIMPLE_HOME_BIO_FONT_SIZE:
    process.env.NEXT_PUBLIC_THEME_SIMPLE_HOME_BIO_FONT_SIZE || 16,

  SIMPLE_POST_AD_ENABLE: process.env.NEXT_PUBLIC_SIMPLE_POST_AD_ENABLE || false, // 文章列表是否插入广告

  SIMPLE_POST_COVER_ENABLE: process.env.NEXT_PUBLIC_SIMPLE_POST_COVER_ENABLE || false, // 是否展示博客封面
  SIMPLE_POST_TITLE_COVER_ENABLE:
    process.env.NEXT_PUBLIC_SIMPLE_POST_TITLE_COVER_ENABLE || false, // 文章详情标题是否使用 Notion 头图作为底图

  SIMPLE_ARTICLE_RECOMMEND_POSTS: process.env.NEXT_PUBLIC_SIMPLE_ARTICLE_RECOMMEND_POSTS || true, // 文章详情底部显示推荐
  SIMPLE_HIDE_RIGHT_SIDEBAR_ON_PAGES:
    process.env.NEXT_PUBLIC_SIMPLE_HIDE_RIGHT_SIDEBAR_ON_PAGES || true, // Notion Page 类型页面隐藏右侧栏
  SIMPLE_HIDE_RIGHT_SIDEBAR_ON_HOME:
    process.env.NEXT_PUBLIC_SIMPLE_HIDE_RIGHT_SIDEBAR_ON_HOME || true, // 首页隐藏右侧栏
  SIMPLE_RIGHT_SIDEBAR_ONLY_HOME:
    process.env.NEXT_PUBLIC_SIMPLE_RIGHT_SIDEBAR_ONLY_HOME || false, // 仅在首页显示右侧栏

  // 菜单配置
  SIMPLE_MENU_CATEGORY: true, // 显示分类
  SIMPLE_MENU_TAG: true, // 显示标签
  SIMPLE_MENU_ARCHIVE: true, // 显示归档
  SIMPLE_MENU_SEARCH: true // 显示搜索
}
export default CONFIG
