const CONFIG = {
  // Brand and homepage
  EDITORIAL_KICKER:
    process.env.NEXT_PUBLIC_EDITORIAL_KICKER || 'ESSAYS · NOTES · IDEAS',
  EDITORIAL_HERO_TITLE:
    process.env.NEXT_PUBLIC_EDITORIAL_HERO_TITLE || '',
  EDITORIAL_HERO_DESCRIPTION:
    process.env.NEXT_PUBLIC_EDITORIAL_HERO_DESCRIPTION || '',
  EDITORIAL_SHOW_HERO:
    process.env.NEXT_PUBLIC_EDITORIAL_SHOW_HERO !== 'false',

  // Light palette (shared theme-console token names)
  EDITORIAL_COLOR_PRIMARY:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_PRIMARY || '#c96442',
  EDITORIAL_COLOR_BG:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_BG || '#f5f4ed',
  EDITORIAL_COLOR_CARD:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_CARD || '#faf9f5',
  EDITORIAL_COLOR_TEXT:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_TEXT || '#1d1b18',
  EDITORIAL_COLOR_TEXT_SECONDARY:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_TEXT_SECONDARY || '#6b6560',
  EDITORIAL_COLOR_BORDER:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_BORDER || '#e3e0d5',

  // Dark palette
  EDITORIAL_COLOR_PRIMARY_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_PRIMARY_DARK || '#dc8a68',
  EDITORIAL_COLOR_BG_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_BG_DARK || '#141413',
  EDITORIAL_COLOR_CARD_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_CARD_DARK || '#1d1c19',
  EDITORIAL_COLOR_TEXT_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_TEXT_DARK || '#ece9df',
  EDITORIAL_COLOR_TEXT_SECONDARY_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_TEXT_SECONDARY_DARK || '#aaa59b',
  EDITORIAL_COLOR_BORDER_DARK:
    process.env.NEXT_PUBLIC_EDITORIAL_COLOR_BORDER_DARK || '#34322d',

  // Post list and article
  EDITORIAL_POST_LIST_COVER:
    process.env.NEXT_PUBLIC_EDITORIAL_POST_LIST_COVER !== 'false',
  EDITORIAL_POST_LIST_CATEGORY:
    process.env.NEXT_PUBLIC_EDITORIAL_POST_LIST_CATEGORY !== 'false',
  EDITORIAL_POST_LIST_TAG:
    process.env.NEXT_PUBLIC_EDITORIAL_POST_LIST_TAG === 'true',
  EDITORIAL_ARTICLE_CATEGORY:
    process.env.NEXT_PUBLIC_EDITORIAL_ARTICLE_CATEGORY !== 'false',
  EDITORIAL_ARTICLE_TAG:
    process.env.NEXT_PUBLIC_EDITORIAL_ARTICLE_TAG !== 'false',
  EDITORIAL_ARTICLE_RECOMMEND_POSTS:
    process.env.NEXT_PUBLIC_EDITORIAL_ARTICLE_RECOMMEND_POSTS !== 'false',
  EDITORIAL_TOC_ENABLE:
    process.env.NEXT_PUBLIC_EDITORIAL_TOC_ENABLE !== 'false',

  // Navigation
  EDITORIAL_MENU_CATEGORY:
    process.env.NEXT_PUBLIC_EDITORIAL_MENU_CATEGORY !== 'false',
  EDITORIAL_MENU_TAG:
    process.env.NEXT_PUBLIC_EDITORIAL_MENU_TAG !== 'false',
  EDITORIAL_MENU_ARCHIVE:
    process.env.NEXT_PUBLIC_EDITORIAL_MENU_ARCHIVE !== 'false',
  EDITORIAL_MENU_SEARCH:
    process.env.NEXT_PUBLIC_EDITORIAL_MENU_SEARCH !== 'false',

  // Widgets
  EDITORIAL_WIDGET_TO_TOP:
    process.env.NEXT_PUBLIC_EDITORIAL_WIDGET_TO_TOP !== 'false'
}

export default CONFIG
